<a href="https://colab.research.google.com/github/KanoonGammy/Python-for-investing/blob/All/3_Workshop_Simple_Moving_Average_Cross_Over.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install yfinance

In [ ]:
import yfinance as yf
data = yf.download('BTC-USD' , start = "2020-01-01" , end = "2022-01-01")

def sma_crossover(df):
    df['sma_12'] = df.Close.rolling(12).mean()
    df['sma_26'] = df.Close.rolling(26).mean()
    df['trend'] = df['sma_12'] > df['sma_26']
    df.loc[(df['trend'] != df['trend'].shift(1)) & (df['trend'] == True), 'action'] = 'buy'
    df.loc[(df['trend'] != df['trend'].shift(1)) & (df['trend'] == False), 'action'] = 'sell'
    return df

sma_crossover(data)

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume,sma_12,sma_26,trend,action
Date,,,,,,,,,,
2020-01-01,7194.892090,7254.330566,7174.944336,7200.174316,7200.174316,18565664997,NaN,NaN,False,sell
2020-01-02,7202.551270,7212.155273,6935.270020,6985.470215,6985.470215,20802083465,NaN,NaN,False,NaN
2020-01-03,6984.428711,7413.715332,6914.996094,7344.884277,7344.884277,28111481032,NaN,NaN,False,NaN
2020-01-04,7345.375488,7427.385742,7309.514160,7410.656738,7410.656738,18444271275,NaN,NaN,False,NaN
2020-01-05,7410.451660,7544.497070,7400.535645,7411.317383,7411.317383,19725074095,NaN,NaN,False,NaN
...,...,...,...,...,...,...,...,...,...,...
2021-12-27,50802.609375,51956.328125,50499.468750,50640.417969,50640.417969,24324345758,48779.607747,49323.519982,False,NaN
2021-12-28,50679.859375,50679.859375,47414.210938,47588.855469,47588.855469,33430376883,48773.226888,48981.636869,False,NaN
2021-12-29,47623.871094,48119.742188,46201.496094,46444.710938,46444.710938,30049226299,48793.440755,48706.500901,True,buy
2021-12-30,46490.605469,47879.964844,46060.312500,47178.125000,47178.125000,26686491018,48820.886393,48628.709435,True,NaN
2021-12-31,47169.371094,48472.527344,45819.953125,46306.445312,46306.445312,36974172400,48787.505534,48510.924730,True,NaN

In [ ]:
df = sma_crossover(data)
df[df['action'].notnull()]

,Open,High,Low,Close,Adj Close,Volume,sma_12,sma_26,trend,action
Date,,,,,,,,,,
2020-01-01,7194.892090,7254.330566,7174.944336,7200.174316,7200.174316,18565664997,NaN,NaN,False,sell
2020-01-26,8364.410156,8602.401367,8325.498047,8596.830078,8596.830078,22177678796,8667.494141,8216.262432,True,buy
2020-02-26,9338.290039,9354.778320,8704.426758,8820.522461,8820.522461,50420050762,9665.366699,9739.787898,False,sell
2020-04-02,6606.776367,7088.247559,6595.918457,6793.624512,6793.624512,47660646124,6440.149943,6319.826209,True,buy
2020-05-29,9528.355469,9573.666992,9379.338867,9439.124023,9439.124023,32896642044,9260.872396,9278.669208,False,sell
2020-06-03,9533.760742,9682.859375,9471.846680,9656.717773,9656.717773,25007459262,9366.899821,9337.768893,True,buy
2020-06-20,9290.959961,9394.971680,9247.379883,9332.340820,9332.340820,17130541557,9485.972249,9537.617939,False,sell
2020-07-16,9191.980469,9214.312500,9088.947266,9132.227539,9132.227539,15713967523,9251.295166,9247.239896,True,buy
2020-08-29,11541.054688,11585.640625,11466.292969,11506.865234,11506.865234,17485597759,11630.742269,11683.551457,False,sell
2020-09-24,10248.786133,10771.056641,10231.490234,10760.066406,10760.066406,47144380902,10725.801432,10717.043758,True,buy
2020-10-07,10603.355469,10680.507812,10562.506836,10668.968750,10668.968750,37799458436,10695.485921,10699.628305,False,sell
2020-10-10,11059.142578,11442.210938,11056.940430,11296.361328,11296.361328,22877978588,10782.224202,10770.002930,True,buy
2021-01-25,32285.798828,34802.742188,32087.787109,32366.392578,32366.392578,59897054838,34732.051432,34940.157903,False,sell
2021-02-06,38138.386719,40846.546875,38138.386719,39266.011719,39266.011719,71326033653,34918.725423,34886.486253,True,buy
2021-03-05,48527.031250,49396.429688,46542.515625,48927.304688,48927.304688,48625928883,48627.821615,49341.074369,False,sell
2021-03-11,55963.179688,58091.062500,54484.593750,57805.121094,57805.121094,56772343595,51014.841797,50913.687200,True,buy
2021-03-31,58930.277344,59930.027344,57726.417969,58918.832031,58918.832031,65520826225,56019.322917,56111.589393,False,sell
2021-04-05,58760.875000,59891.296875,57694.824219,59057.878906,59057.878906,60706272115,57354.408203,57292.442458,True,buy
2021-04-23,51739.808594,52120.792969,47714.664062,51093.652344,51093.652344,86668667320,58104.393555,58367.243990,False,sell
2021-05-09,58877.390625,59210.882812,56482.003906,58232.316406,58232.316406,65906690347,56611.330729,56203.914363,True,buy
2021-05-15,49855.496094,50639.664062,46664.140625,46760.187500,46760.187500,59161047474,54134.864909,54182.801082,False,sell
2021-06-17,38341.421875,39513.671875,37439.675781,38053.503906,38053.503906,37096670047,37162.793620,37107.821815,True,buy
2021-06-24,33682.800781,35228.851562,32385.214844,34662.437500,34662.437500,33123368116,36316.033691,36328.806716,False,sell
2021-07-28,39503.187500,40816.070312,38862.437500,39995.906250,39995.906250,38702404695,34028.618652,33709.802284,True,buy
2021-09-13,46057.214844,46598.679688,43591.320312,44963.074219,44963.074219,40969943253,47840.860026,48130.349760,False,sell
2021-10-06,51486.664062,55568.464844,50488.191406,55361.449219,55361.449219,49034730168,46214.017578,45826.967097,True,buy
2021-11-21,59730.507812,60004.425781,58618.929688,58730.476562,58730.476562,26123447605,61801.167969,62127.929988,False,sell
2021-12-29,47623.871094,48119.742188,46201.496094,46444.710938,46444.710938,30049226299,48793.440755,48706.500901,True,buy